# Generated by Django 3.1.2 on 2020-11-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201105_1300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
