# Generated by Django 3.1.2 on 2020-11-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='owners',
        ),
    ]
