# Generated by Django 3.1.2 on 2020-11-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_purchase_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='byer',
            new_name='buyer',
        ),
    ]
