version: '3.3'

volumes:
  postgres_data:
  static-data:
  media-data:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: vilbert55/foodgram:latest
    restart: always
    expose:
      - 8000
    volumes:
      - static-data:/code/foodgram_project/static/
      - media-data:/code/foodgram_project/media/
    depends_on:
      - db
    command: bash -c "cd foodgram_project && python manage.py collectstatic --noinput && python manage.py makemigrations --noinput && python manage.py migrate --noinput && gunicorn foodgram_project.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - ./.env

  nginx:
    restart: always
    image: nginx:1.18.0
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=80
    volumes:
      - ./docker.conf:/etc/nginx/conf.d/docker.conf
      - static-data:/static/
      - media-data:/media/
    depends_on:
      - web       
